### ISSUE TITLE
Add covid cases slots, latest news.

### ISSUE THREAD

**Issue by Sidcipher** [CareerDevelopmentHub/Healer#1]
In the COVID-19 section, add World Stats, country stats and the latest news.
Users should be able to search the country and they can get the stats.

**Comment by kaal-coder** [comment]
Hello @Sidcipher 
Can I work on this issue ?

**Comment by Sidcipher** [comment]
Yeah sure. 
Remember to share a screenshot as a preview of the page before make put a PR.

**Comment by kaal-coder** [comment]
Okay Buddy. Thank you

**Comment by kaal-coder** [comment]
![image](https://user-images.githubusercontent.com/85815858/194139321-22af69cf-680b-40e3-83fa-c74750d1ebfc.png)


The default stats are of India in the country section.

![image](https://user-images.githubusercontent.com/85815858/194139496-bbcf550c-618a-4e8b-9354-0fc040e39061.png)

News, which will automatically get updated daily.

**Comment by Sidcipher** [comment]
Great. It is as expected. You can make a PR.
