### ISSUE TITLE
Add animation in home page and improve navigation bar.

### ISSUE THREAD

**Issue by Sidcipher** [CareerDevelopmentHub/Healer#2]

**Comment by SmrutiRanjan-L** [comment]
Can I do this sir ?

**Comment by Sidcipher** [comment]
Yeah, you can.
Provide a preview of changes you did after completion and before making a PR/

**Comment by SmrutiRanjan-L** [comment]
Okay !

**Comment by SmrutiRanjan-L** [comment]
https://user-images.githubusercontent.com/81686733/194142007-5898cc60-4030-4d30-ac9b-1e473c7d6913.mp4

Preview of changes

**Comment by Sidcipher** [comment]
Great work. It is as expected.
