### ISSUE TITLE
we can add video sources as an awareness 

### ISSUE THREAD

**Issue by Swastik200** [CareerDevelopmentHub/Healer#5]

**Comment by Sidcipher** [comment]
Where are you planning to add it, please explain more about it?
And the change you made is very less and not attractive.
Before making a PR, make sure to send a preview in [issues](https://github.com/CareerDevelopmentHub/Healer/issues).

**Comment by Swastik200** [comment]
We can add a short movie link and make images float just like features

**Comment by Sidcipher** [comment]
Nope. That doesn't match our website content for now. You can hop on to other [issues](https://github.com/CareerDevelopmentHub/Healer/issues)!
